import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import {
  type ColumnKey,
  type ReportConfig,
  type ReportResult,
  COLUMN_LABELS,
  columnValue,
  isNumericColumn,
} from '@/lib/reportBuilder';

export interface ReportBuilderPDFProps {
  config: ReportConfig;
  displayColumns: ColumnKey[];
  result: ReportResult;
  institutionName: string;
  termName: string;
  generatedBy: string;
}

const S = StyleSheet.create({
  page: { fontFamily: 'Helvetica', fontSize: 9, color: '#1a1a1a', padding: 28 },
  institution: { fontSize: 13, fontFamily: 'Helvetica-Bold' },
  title: { fontSize: 11, fontFamily: 'Helvetica-Bold', marginTop: 6, color: '#1d4ed8' },
  meta: { fontSize: 8, color: '#555', marginTop: 2 },
  statBox: { marginTop: 24, alignItems: 'center' },
  statValue: { fontSize: 30, fontFamily: 'Helvetica-Bold', color: '#0284c7' },
  statLabel: { fontSize: 9, color: '#555', marginTop: 4 },
  headerRow: {
    flexDirection: 'row',
    borderBottom: '1pt solid #1d4ed8',
    marginTop: 16,
    paddingBottom: 3,
  },
  row: { flexDirection: 'row', borderBottom: '0.5pt solid #ddd', paddingVertical: 3 },
  th: { fontSize: 8, fontFamily: 'Helvetica-Bold', paddingHorizontal: 3 },
  td: { fontSize: 8, paddingHorizontal: 3 },
  footer: { position: 'absolute', bottom: 16, left: 28, right: 28, fontSize: 7, color: '#999' },
});

function populationLabel(config: ReportConfig): string {
  switch (config.population.type) {
    case 'class':
      return 'Class';
    case 'grade':
      return `Grade ${config.population.grade ?? ''}`.trim();
    case 'cohort':
      return 'Cohort';
    case 'house':
      return 'House';
    default:
      return 'Whole institution';
  }
}

export const ReportBuilderPDF = ({
  config,
  displayColumns,
  result,
  institutionName,
  termName,
  generatedBy,
}: ReportBuilderPDFProps) => {
  // Even column widths, with name columns given more room.
  const weight = (k: ColumnKey) => (k === 'studentName' ? 2 : 1);
  const totalWeight = displayColumns.reduce((s, k) => s + weight(k), 0) || 1;
  const colHeader = (k: ColumnKey) =>
    k === 'subject' ? config.focusSubjectName ?? 'Subject' : COLUMN_LABELS[k];

  return (
    <Document>
      <Page size="A4" style={S.page}>
        <Text style={S.institution}>{institutionName || 'Institution'}</Text>
        <Text style={S.title}>{config.name}</Text>
        <Text style={S.meta}>
          {termName ? `Term: ${termName}  ·  ` : ''}Population: {populationLabel(config)}  ·{' '}
          {result.matchedCount} of {result.total} matched
        </Text>

        {config.output === 'percentage' ? (
          <View style={S.statBox}>
            <Text style={S.statValue}>
              {result.percentage != null ? `${result.percentage.toFixed(1)}%` : '—'}
            </Text>
            <Text style={S.statLabel}>
              {result.matchedCount} of {result.total} students matched
            </Text>
          </View>
        ) : (
          <View>
            <View style={S.headerRow}>
              {displayColumns.map((k) => (
                <Text
                  key={k}
                  style={[S.th, { flexGrow: weight(k) / totalWeight, flexBasis: 0, textAlign: isNumericColumn(k) ? 'right' : 'left' }]}
                >
                  {colHeader(k)}
                </Text>
              ))}
            </View>
            {result.matched.map((card) => (
              <View key={card.id} style={S.row} wrap={false}>
                {displayColumns.map((k) => (
                  <Text
                    key={k}
                    style={[S.td, { flexGrow: weight(k) / totalWeight, flexBasis: 0, textAlign: isNumericColumn(k) ? 'right' : 'left' }]}
                  >
                    {columnValue(card, k, config.focusSubjectId)}
                  </Text>
                ))}
              </View>
            ))}
          </View>
        )}

        <Text
          style={S.footer}
          render={({ pageNumber, totalPages }) =>
            `Generated by ${generatedBy || '—'} · ${new Date().toLocaleDateString('en-US', {
              month: 'long',
              day: 'numeric',
              year: 'numeric',
            })}  ·  Page ${pageNumber} / ${totalPages}`
          }
          fixed
        />
      </Page>
    </Document>
  );
};
