export const COMMENT_KEY: readonly string[] = [
  "A very keen student who has maintained a high standard of performance.",
  "A hardworking and capable student.",
  "A dependable and eager student who takes pride in his/her work.",
  "Works consistently and is making some progress.",
  "Shows interest and is making some progress.",
  "Fair performance but can do better.",
  "Tries but finds the subject difficult.",
  "Has a good grasp of the facts but unable to express them effectively.",
  "Has potential but does not work hard enough.",
  "Shows little interest in the subject.",
  "Usually works well, but has difficulty with an examination.",
  "Needs to read more.",
  "Must pay more attention to details.",
  "With greater application his/her work should improve.",
  "Very confident.",
  "Demonstrates initiative.",
  "Disappointing exam results.",
  "Slow, needs extra help.",
  "Disruptive in class.",
  "Needs individual attention.",
] as const;
