// TEMPORARY MOCK DATA — replace each export with Firestore queries as data layer is built out

// ─── Data mode ──────────────────────────────────────────────────────────────
// VITE_USE_MOCK_DATA (env var) sets the per-environment default.
// localStorage key 'sms_data_mode_v2' ('mock' | 'blank' | 'live') overrides it per session.
// Key renamed from 'sms_data_mode' to avoid misinterpreting the old 'live' value (which meant
// blank/empty) as the new 'live' value (which fires real Firestore queries).
// Changing the key requires a page reload to take effect.
export type DataMode = 'mock' | 'blank' | 'live';

const _valid: DataMode[] = ['mock', 'blank', 'live'];

const _defaultMode: DataMode =
  import.meta.env.VITE_USE_MOCK_DATA === 'true' ? 'mock' : 'blank';

const _stored =
  typeof localStorage !== 'undefined'
    ? localStorage.getItem('sms_data_mode_v2')
    : null;

const _override =
  _stored && (_valid as string[]).includes(_stored)
    ? (_stored as DataMode)
    : null;

export const DATA_MODE: DataMode = _override ?? _defaultMode;
export const USE_MOCK = DATA_MODE === 'mock'; // backwards compat — existing consumers unchanged

const _teachersData = [
  {
    id: 1,
    teacherId: "T-10001",
    name: "John Doe",
    email: "john@doe.com",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0101",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
    department: "Mathematics",
    emergencyContact: "Emma Doe - 555-0201",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 88%, Attendance 95%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 2,
    teacherId: "T-10002",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0102",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "456 Oak Ave, Anytown, USA",
    department: "Science",
    emergencyContact: "Jim Doe - 555-0202",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 82%, Attendance 93%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 3,
    teacherId: "T-10003",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0103",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "789 Pine Rd, Anytown, USA",
    department: "Science",
    emergencyContact: "Sara Geller - 555-0203",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 90%, Attendance 97%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 4,
    teacherId: "T-10004",
    name: "Jay French",
    email: "jay@gmail.com",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0104",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "321 Elm St, Anytown, USA",
    department: "Humanities",
    emergencyContact: "Amy French - 555-0204",
    schedule: "Mon-Thu, 08:00 AM - 04:00 PM",
    metrics: "Avg score 79%, Attendance 91%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 5,
    teacherId: "T-10005",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0105",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "654 Maple Dr, Anytown, USA",
    department: "Arts",
    emergencyContact: "Tom Smith - 555-0205",
    schedule: "Mon-Fri, 09:00 AM - 04:00 PM",
    metrics: "Avg score 85%, Attendance 94%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 6,
    teacherId: "T-10006",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0106",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "987 Cedar Ln, Anytown, USA",
    department: "Science",
    emergencyContact: "Luis Santiago - 555-0206",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 87%, Attendance 96%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 7,
    teacherId: "T-10007",
    name: "Allen Black",
    email: "allen@black.com",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0107",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "147 Birch Blvd, Anytown, USA",
    department: "Languages",
    emergencyContact: "Nora Black - 555-0207",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 83%, Attendance 92%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 8,
    teacherId: "T-10008",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0108",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "258 Walnut Way, Anytown, USA",
    department: "Mathematics",
    emergencyContact: "Marco Castro - 555-0208",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 91%, Attendance 98%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 9,
    teacherId: "T-10009",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0109",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "369 Spruce St, Anytown, USA",
    department: "Languages",
    emergencyContact: "Diane Briggs - 555-0209",
    schedule: "Mon-Thu, 08:00 AM - 04:00 PM",
    metrics: "Avg score 84%, Attendance 93%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
  {
    id: 10,
    teacherId: "T-10010",
    name: "John Glover",
    email: "john@glover.com",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0110",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "741 Willow Ct, Anytown, USA",
    department: "Science",
    emergencyContact: "Beth Glover - 555-0210",
    schedule: "Mon-Fri, 08:00 AM - 03:00 PM",
    metrics: "Avg score 86%, Attendance 95%",
    status: "Active",
    linkedAccounts: "Google Classroom",
  },
];

const _studentsData = [
  {
    id: 1,
    studentId: "S-20001",
    name: "John Doe",
    email: "john.doe@student.edu",
    photo: "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0301",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
    homeroom: "Room 12B",
    guardians: ["James Doe", "Linda Doe"],
    attendanceSummary: "96% YTD",
    gpa: "3.6 GPA",
    emergencyContact: "James Doe - 555-0351",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 2,
    studentId: "S-20002",
    name: "Jane Doe",
    email: "jane.doe@student.edu",
    photo: "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0302",
    grade: 5,
    class: "5A",
    address: "456 Oak Ave, Anytown, USA",
    homeroom: "Room 7A",
    guardians: ["James Doe", "Linda Doe"],
    attendanceSummary: "92% YTD",
    gpa: "3.2 GPA",
    emergencyContact: "Linda Doe - 555-0352",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 3,
    studentId: "S-20003",
    name: "Mike Geller",
    email: "mike.geller@student.edu",
    photo: "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0303",
    grade: 4,
    class: "5A",
    address: "789 Pine Rd, Anytown, USA",
    homeroom: "Room 9C",
    guardians: ["Robert Geller"],
    attendanceSummary: "98% YTD",
    gpa: "3.8 GPA",
    emergencyContact: "Robert Geller - 555-0353",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 4,
    studentId: "S-20004",
    name: "Jay French",
    email: "jay.french@student.edu",
    photo: "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0304",
    grade: 3,
    class: "5A",
    address: "321 Elm St, Anytown, USA",
    homeroom: "Room 11B",
    guardians: ["Maria French"],
    attendanceSummary: "88% YTD",
    gpa: "2.9 GPA",
    emergencyContact: "Maria French - 555-0354",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 5,
    studentId: "S-20005",
    name: "Jane Smith",
    email: "jane.smith@student.edu",
    photo: "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0305",
    grade: 5,
    class: "5A",
    address: "654 Maple Dr, Anytown, USA",
    homeroom: "Room 8A",
    guardians: ["David Smith", "Karen Smith"],
    attendanceSummary: "94% YTD",
    gpa: "3.5 GPA",
    emergencyContact: "David Smith - 555-0355",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 6,
    studentId: "S-20006",
    name: "Anna Santiago",
    email: "anna.santiago@student.edu",
    photo: "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0306",
    grade: 6,
    class: "5A",
    address: "987 Cedar Ln, Anytown, USA",
    homeroom: "Room 10C",
    guardians: ["Pedro Santiago"],
    attendanceSummary: "97% YTD",
    gpa: "3.7 GPA",
    emergencyContact: "Pedro Santiago - 555-0356",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 7,
    studentId: "S-20007",
    name: "Allen Black",
    email: "allen.black@student.edu",
    photo: "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0307",
    grade: 4,
    class: "5A",
    address: "147 Birch Blvd, Anytown, USA",
    homeroom: "Room 6B",
    guardians: ["Thomas Black", "Helen Black"],
    attendanceSummary: "90% YTD",
    gpa: "3.1 GPA",
    emergencyContact: "Thomas Black - 555-0357",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 8,
    studentId: "S-20008",
    name: "Ophelia Castro",
    email: "ophelia.castro@student.edu",
    photo: "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0308",
    grade: 6,
    class: "5A",
    address: "258 Walnut Way, Anytown, USA",
    homeroom: "Room 14A",
    guardians: ["Miguel Castro"],
    attendanceSummary: "99% YTD",
    gpa: "3.9 GPA",
    emergencyContact: "Miguel Castro - 555-0358",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 9,
    studentId: "S-20009",
    name: "Derek Briggs",
    email: "derek.briggs@student.edu",
    photo: "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0309",
    grade: 3,
    class: "5A",
    address: "369 Spruce St, Anytown, USA",
    homeroom: "Room 5C",
    guardians: ["Frank Briggs", "Susan Briggs"],
    attendanceSummary: "93% YTD",
    gpa: "3.4 GPA",
    emergencyContact: "Frank Briggs - 555-0359",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
  {
    id: 10,
    studentId: "S-20010",
    name: "John Glover",
    email: "john.glover@student.edu",
    photo: "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "555-0310",
    grade: 5,
    class: "5A",
    address: "741 Willow Ct, Anytown, USA",
    homeroom: "Room 13B",
    guardians: ["William Glover"],
    attendanceSummary: "95% YTD",
    gpa: "3.6 GPA",
    emergencyContact: "William Glover - 555-0360",
    status: "Active",
    linkedAccounts: "Student Portal",
  },
];

const _parentsData = [
  {
    id: 1,
    parentId: "P-1001",
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "555-0401",
    address: "123 Main St, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "On track (last term)",
    childAttendance: "Average 96%",
    emergencyContact: "Sarah Doe - 555-0451",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 2,
    parentId: "P-1002",
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "555-0402",
    address: "456 Oak Ave, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "Needs attention",
    childAttendance: "Average 89%",
    emergencyContact: "Mark Doe - 555-0452",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 3,
    parentId: "P-1003",
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "555-0403",
    address: "789 Pine Rd, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "Excellent (last term)",
    childAttendance: "Average 99%",
    emergencyContact: "Beth Geller - 555-0453",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 4,
    parentId: "P-1004",
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "jay@french.com",
    phone: "555-0404",
    address: "321 Elm St, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "On track (last term)",
    childAttendance: "Average 93%",
    emergencyContact: "Tim French - 555-0454",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 5,
    parentId: "P-1005",
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "jane@smith.com",
    phone: "555-0405",
    address: "654 Maple Dr, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Guardian",
    studentPerformance: "On track (last term)",
    childAttendance: "Average 95%",
    emergencyContact: "Ann Smith - 555-0455",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 6,
    parentId: "P-1006",
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "anna@santiago.com",
    phone: "555-0406",
    address: "987 Cedar Ln, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "Excellent (last term)",
    childAttendance: "Average 98%",
    emergencyContact: "Rosa Santiago - 555-0456",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 7,
    parentId: "P-1007",
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "allen@black.com",
    phone: "555-0407",
    address: "147 Birch Blvd, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "On track (last term)",
    childAttendance: "Average 91%",
    emergencyContact: "Carl Black - 555-0457",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 8,
    parentId: "P-1008",
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "ophelia@castro.com",
    phone: "555-0408",
    address: "258 Walnut Way, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "Excellent (last term)",
    childAttendance: "Average 99%",
    emergencyContact: "Nina Castro - 555-0458",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 9,
    parentId: "P-1009",
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "derek@briggs.com",
    phone: "555-0409",
    address: "369 Spruce St, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Guardian",
    studentPerformance: "Needs attention",
    childAttendance: "Average 88%",
    emergencyContact: "Ed Briggs - 555-0459",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
  {
    id: 10,
    parentId: "P-1010",
    name: "John Glover",
    students: ["Stella Scott"],
    email: "john@glover.com",
    phone: "555-0410",
    address: "741 Willow Ct, Anytown, USA",
    photo: "/avatar.png",
    relationship: "Parent / Guardian",
    studentPerformance: "On track (last term)",
    childAttendance: "Average 94%",
    emergencyContact: "Vera Glover - 555-0460",
    status: "Active",
    linkedAccounts: "Family Portal",
  },
];

const _subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

const _classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 6,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

const _lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

const _examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

const _assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

const _resultsData = [
  {
    id: 1,
    studentId: "S-20001",
    studentName: "John Doe",
    teacherId: "T-10001",
    teacherName: "John Doe",
    classId: "1",
    className: "1A",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-mathematics",
    assessmentName: "Midterm Exam",
    score: 78,
    maxScore: 100,
    date: "2026-03-15",
  },
  {
    id: 2,
    studentId: "S-20002",
    studentName: "Jane Doe",
    teacherId: "T-10002",
    teacherName: "Jane Doe",
    classId: "2",
    className: "2B",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-science",
    assessmentName: "Lab Report",
    score: 85,
    maxScore: 100,
    date: "2026-03-20",
  },
  {
    id: 3,
    studentId: "S-20003",
    studentName: "Mike Geller",
    teacherId: "T-10001",
    teacherName: "John Doe",
    classId: "3",
    className: "3C",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-mathematics",
    assessmentName: "Assignment 1",
    score: 64,
    maxScore: 80,
    date: "2026-02-28",
  },
  {
    id: 4,
    studentId: "S-20001",
    studentName: "John Doe",
    teacherId: "T-10001",
    teacherName: "John Doe",
    classId: "1",
    className: "1A",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-mathematics",
    assessmentName: "Final Exam",
    score: 91,
    maxScore: 100,
    date: "2026-05-10",
  },
  {
    id: 5,
    studentId: "S-20002",
    studentName: "Jane Doe",
    teacherId: "T-10003",
    teacherName: "Bob Brown",
    classId: "4",
    className: "4B",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-humanities",
    assessmentName: "History Quiz",
    score: 52,
    maxScore: 80,
    date: "2026-03-05",
  },
  {
    id: 6,
    studentId: "S-20003",
    studentName: "Mike Geller",
    teacherId: "T-10002",
    teacherName: "Jane Doe",
    classId: "2",
    className: "2B",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-science",
    assessmentName: "Chemistry Lab",
    score: 88,
    maxScore: 100,
    date: "2026-04-08",
  },
  {
    id: 7,
    studentId: "S-20001",
    studentName: "John Doe",
    teacherId: "T-10003",
    teacherName: "Bob Brown",
    classId: "3",
    className: "3C",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-humanities",
    assessmentName: "Geography Project",
    score: 76,
    maxScore: 100,
    date: "2026-04-22",
  },
  {
    id: 8,
    studentId: "S-20002",
    studentName: "Jane Doe",
    teacherId: "T-10002",
    teacherName: "Jane Doe",
    classId: "5",
    className: "5A",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-science",
    assessmentName: "Physics Test",
    score: 92,
    maxScore: 100,
    date: "2026-04-30",
  },
  {
    id: 9,
    studentId: "S-20003",
    studentName: "Mike Geller",
    teacherId: "T-10001",
    teacherName: "John Doe",
    classId: "1",
    className: "1A",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-mathematics",
    assessmentName: "Math Assignment",
    score: 55,
    maxScore: 75,
    date: "2026-02-14",
  },
  {
    id: 10,
    studentId: "S-20001",
    studentName: "John Doe",
    teacherId: "T-10002",
    teacherName: "Jane Doe",
    classId: "4",
    className: "4B",
    termId: "term-1",
    institutionId: "mock-inst",
    departmentId: "dept-science",
    assessmentName: "Science Quiz",
    score: 70,
    maxScore: 80,
    date: "2026-03-28",
  },
];

const _eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

const _announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
const _calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];

const _activityLogData = [
  {
    eventType: 'photo_update' as const,
    detail: 'Profile header',
    timestamp: '2026-01-25T14:10:00.000Z',
    uid: 'mock-uid',
    institutionId: 'mock-inst',
  },
  {
    eventType: 'notification_change' as const,
    detail: 'Email + SMS enabled',
    timestamp: '2026-01-20T11:05:00.000Z',
    uid: 'mock-uid',
    institutionId: 'mock-inst',
  },
];

const _auditLogData = [
  {
    eventType: 'password_reset' as const,
    detail: 'User: Sarah Brewer',
    targetUid: 'mock-uid-2',
    targetName: 'Sarah Brewer',
    performedBy: 'mock-uid',
    performedByName: 'Admin',
    timestamp: '2026-01-28T16:45:00.000Z',
    institutionId: 'mock-inst',
  },
  {
    eventType: 'role_change' as const,
    detail: 'Teacher to Department Lead',
    targetUid: 'mock-uid-3',
    targetName: 'Derek Briggs',
    performedBy: 'mock-uid',
    performedByName: 'Admin',
    timestamp: '2026-01-18T10:05:00.000Z',
    institutionId: 'mock-inst',
  },
];

const _termsData = [
  {
    id: "term-1",
    name: "Spring 2026",
    institutionId: "mock-inst",
    startDate: "2026-01-10",
    endDate: "2026-05-30",
    status: "active" as const,
  },
  {
    id: "term-2",
    name: "Fall 2025",
    institutionId: "mock-inst",
    startDate: "2025-08-25",
    endDate: "2025-12-20",
    status: "closed" as const,
  },
  {
    id: "term-3",
    name: "Fall 2026",
    institutionId: "mock-inst",
    startDate: "2026-08-24",
    endDate: "2026-12-19",
    status: "upcoming" as const,
  },
];

// ─── Conditional re-exports ──────────────────────────────────────────────────
// All existing imports in page components remain unchanged.
// When USE_MOCK is false every array is empty, producing blank-data empty states.
export const teachersData      = USE_MOCK ? _teachersData      : [];
export const studentsData      = USE_MOCK ? _studentsData      : [];
export const parentsData       = USE_MOCK ? _parentsData       : [];
export const subjectsData      = USE_MOCK ? _subjectsData      : [];
export const classesData       = USE_MOCK ? _classesData       : [];
export const lessonsData       = USE_MOCK ? _lessonsData       : [];
export const examsData         = USE_MOCK ? _examsData         : [];
export const assignmentsData   = USE_MOCK ? _assignmentsData   : [];
export const resultsData       = USE_MOCK ? _resultsData       : [];
export const eventsData        = USE_MOCK ? _eventsData        : [];
export const announcementsData = USE_MOCK ? _announcementsData : [];
export const calendarEvents    = USE_MOCK ? _calendarEvents    : [];
export const activityLogData   = USE_MOCK ? _activityLogData   : [];
export const auditLogData      = USE_MOCK ? _auditLogData      : [];
export const termsData         = USE_MOCK ? _termsData         : [];
