import { useState, useEffect, Suspense, lazy } from "react";

const PDFPreviewModal = lazy(() => import("@/components/PDFPreviewModal"));
import { doc, getDoc } from "firebase/firestore";
import { db } from "@/lib/firebase";
import { useAuth } from "@/lib/AuthContext";
import Pagination from "@/components/Pagination";
import Table from "@/components/Table";
import TableSearch from "@/components/TableSearch";
import { reportsData, studentsData, termsData } from "@/lib/data";
import { filterByInstitution, filterBySearch, PAGE_SIZE } from "@/lib/utils";
import { generateReport } from "@/lib/generateReport";
import type { ResultDocument, FeedbackCommentDocument } from "@/lib/firebase";

type ReportRow = {
  id: string;
  studentId: string;
  studentName: string;
  termId: string;
  termName: string;
  institutionId: string;
  institutionName: string;
  generatedAt: string;
  generatedBy: string;
  generatedByRole: string;
  gradingSystem: string;
  departmentId?: string;
  grades: ResultDocument[];
  feedback: FeedbackCommentDocument[];
  overallScore: number;
};

const columns = [
  { header: "Student", accessor: "studentName" },
  { header: "Term", accessor: "termName" },
  { header: "Score", accessor: "overallScore" },
  { header: "System", accessor: "gradingSystem", className: "hidden md:table-cell" },
  { header: "Generated At", accessor: "generatedAt", className: "hidden md:table-cell" },
  { header: "Generated By", accessor: "generatedByRole", className: "hidden md:table-cell" },
  { header: "Actions", accessor: "action" },
];

const ReportsPage = () => {
  const { role, institutionId, user } = useAuth();
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [departmentId, setDepartmentId] = useState("");
  const [showGenPanel, setShowGenPanel] = useState(false);
  const [genStudentId, setGenStudentId] = useState("");
  const [genTermId, setGenTermId] = useState("");
  const [generating, setGenerating] = useState(false);
  const [genError, setGenError] = useState<string | null>(null);
  const [showPDF, setShowPDF] = useState(false);
  const [pdfReport, setPdfReport] = useState<ReportRow | null>(null);

  useEffect(() => {
    if (role === "senior_teacher" && user?.uid) {
      getDoc(doc(db, "teachers", user.uid)).then((snap) => {
        if (snap.exists()) setDepartmentId(snap.data().departmentId ?? "");
      });
    }
  }, [role, user]);

  const byInstitution = filterByInstitution(reportsData, institutionId);
  const roleFiltered = (() => {
    if (role === "student") return byInstitution.filter((r) => r.studentId === user?.uid);
    if (role === "parent") return [];
    return byInstitution;
  })();
  const searchedData = filterBySearch(roleFiltered, search, ["studentName", "termName"]);
  const paginatedData = searchedData.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const canGenerate = role === "institution_admin" || role === "senior_teacher";

  const handleGenerate = async (studentId: string, termId: string) => {
    if (!studentId || !termId || !user || !institutionId) return;
    setGenerating(true);
    setGenError(null);
    try {
      await generateReport(
        studentId,
        termId,
        institutionId,
        role === "senior_teacher" ? (departmentId || null) : null,
        user.uid,
        role as "institution_admin" | "senior_teacher",
      );
      setShowGenPanel(false);
      setGenStudentId("");
      setGenTermId("");
    } catch (err) {
      setGenError(err instanceof Error ? err.message : "Report generation failed.");
    } finally {
      setGenerating(false);
    }
  };

  const renderRow = (item: ReportRow) => (
    <tr
      key={item.id}
      className="border-b border-gray-200 dark:border-gray-700 even:bg-slate-50 dark:even:bg-gray-800/60 text-sm hover:bg-lamaPurpleLight dark:hover:bg-gray-800"
    >
      <td className="flex items-center gap-4 p-4">{item.studentName}</td>
      <td>{item.termName}</td>
      <td>{item.overallScore.toFixed(1)}%</td>
      <td className="hidden md:table-cell capitalize">{item.gradingSystem}</td>
      <td className="hidden md:table-cell">{item.generatedAt.slice(0, 10)}</td>
      <td className="hidden md:table-cell capitalize">{item.generatedByRole.replace(/_/g, " ")}</td>
      <td>
        <div className="flex items-center gap-2">
          {canGenerate && (
            <button
              onClick={() => handleGenerate(item.studentId, item.termId)}
              disabled={generating}
              className="text-xs bg-lamaYellow hover:bg-yellow-300 text-gray-700 px-2 py-1 rounded transition-colors disabled:opacity-50"
            >
              Re-generate
            </button>
          )}
          <button
            onClick={() => { setPdfReport(item); setShowPDF(true); }}
            className="text-xs bg-sky-100 hover:bg-sky-200 text-sky-700 px-2 py-1 rounded transition-colors"
          >
            PDF
          </button>
        </div>
      </td>
    </tr>
  );

  return (
    <div className="bg-white dark:bg-gray-800 p-4 rounded-md flex-1 m-4 mt-0">
      {/* TOP */}
      <div className="flex items-center justify-between">
        <h1 className="hidden md:block text-lg font-semibold">Reports</h1>
        <div className="flex flex-col md:flex-row items-center gap-4 w-full md:w-auto">
          <TableSearch value={search} onChange={(v) => { setSearch(v); setPage(1); }} />
          <div className="flex items-center gap-4 self-end">
            <button className="w-8 h-8 flex items-center justify-center rounded-full bg-lamaYellow">
              <img src="/filter.png" alt="" width={14} height={14} />
            </button>
            <button className="w-8 h-8 flex items-center justify-center rounded-full bg-lamaYellow">
              <img src="/sort.png" alt="" width={14} height={14} />
            </button>
            {canGenerate && (
              <button
                onClick={() => { setShowGenPanel((p) => !p); setGenError(null); }}
                className="w-8 h-8 flex items-center justify-center rounded-full bg-lamaYellow"
                title="Generate Report"
              >
                <img src="/create.png" alt="Generate Report" width={14} height={14} />
              </button>
            )}
          </div>
        </div>
      </div>

      {/* GENERATE PANEL */}
      {showGenPanel && canGenerate && (
        <div className="mt-4 p-4 border border-gray-200 dark:border-gray-700 rounded-md bg-gray-50 dark:bg-gray-900">
          <h2 className="text-sm font-semibold mb-3 dark:text-gray-200">Generate Report</h2>
          <div className="flex flex-col sm:flex-row gap-3">
            <select
              value={genStudentId}
              onChange={(e) => setGenStudentId(e.target.value)}
              className="border border-gray-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm bg-white dark:bg-gray-800 dark:text-gray-200 flex-1"
            >
              <option value="">Select student…</option>
              {studentsData.map((s) => (
                <option key={s.id} value={s.studentId}>{s.name}</option>
              ))}
            </select>
            <select
              value={genTermId}
              onChange={(e) => setGenTermId(e.target.value)}
              className="border border-gray-300 dark:border-gray-600 rounded-md px-3 py-2 text-sm bg-white dark:bg-gray-800 dark:text-gray-200 flex-1"
            >
              <option value="">Select term…</option>
              {termsData.map((t) => (
                <option key={t.id} value={t.id}>{t.name}</option>
              ))}
            </select>
            <button
              onClick={() => handleGenerate(genStudentId, genTermId)}
              disabled={!genStudentId || !genTermId || generating}
              className="px-4 py-2 bg-sky-500 hover:bg-sky-600 text-white text-sm rounded-md transition-colors disabled:opacity-50"
            >
              {generating ? "Generating…" : "Generate"}
            </button>
            <button
              onClick={() => { setShowGenPanel(false); setGenError(null); }}
              className="px-4 py-2 bg-gray-200 hover:bg-gray-300 dark:bg-gray-700 dark:hover:bg-gray-600 dark:text-gray-200 text-sm rounded-md transition-colors"
            >
              Cancel
            </button>
          </div>
          {genError && (
            <p className="mt-2 text-xs text-red-500">{genError}</p>
          )}
        </div>
      )}

      {/* LIST */}
      <Table columns={columns} renderRow={renderRow} data={paginatedData} />
      {/* PAGINATION */}
      <Pagination total={searchedData.length} page={page} pageSize={PAGE_SIZE} onPageChange={setPage} />

      {showPDF && pdfReport && (
        <Suspense fallback={
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 text-white text-sm">
            Loading PDF renderer…
          </div>
        }>
          <PDFPreviewModal
            report={pdfReport}
            onClose={() => { setShowPDF(false); setPdfReport(null); }}
          />
        </Suspense>
      )}
    </div>
  );
};

export default ReportsPage;
